GET http://localhost:3000/

###

GET http://localhost:3000/all-films

###

POST http://localhost:3000/create-film
Content-Type: application/json

{
    "titulo": "Uma tarefa qualquer2",
    "genero": "cu2",
    "duracao": "1h 30min",
    "classificacao": "12"
}

###

DELETE http://localhost:3000/delete-film/1