GET http://localhost:3000/

###

GET http://localhost:3000/active-tasks

###

POST http://localhost:3000/create-film
Content-Type: application/json

{
    "titulo": "Uma tarefa qualquer2",
    "genero": "cu2",
    "duracao": "1",
    "classificacao": "12"
}